q = cirq.LineQubit.range(3)
circuit = cirq.Circuit()
circuit.append(cirq.H(q[0]))
circuit.append(cirq.cphase(np.pi/2)(q[1], q[0]))
circuit.append(cirq.cphase(np.pi/4)(q[2], q[0]))
circuit.append(cirq.H(q[1]))
circuit.append(cirq.cphase(np.pi/2)(q[2], q[1]))
circuit.append(cirq.H(q[2]))
circuit.append(cirq.SWAP(q[0], q[2]))