import cirq
q0, q1, q2 = cirq.LineQubit.range(3)
circuit = cirq.Circuit()
circuit.append(cirq.X(q2))
circuit.append(cirq.H(q0))
circuit.append(cirq.H(q1))
circuit.append(cirq.H(q2))
circuit.append(cirq.CNOT(q0, q2))
circuit.append(cirq.CNOT(q1, q2))
circuit.append(cirq.H(q0))
circuit.append(cirq.H(q1))
circuit.append(cirq.measure(q0, key='m0'))
circuit.append(cirq.measure(q1, key='m1'))