from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
qr = QuantumRegister(3)
cr = ClassicalRegister(2)
qc = QuantumCircuit(qr, cr)
qc.x(qr[2])
qc.h(qr[0])
qc.h(qr[1])
qc.h(qr[2])
qc.cx(qr[0], qr[2])
qc.cx(qr[1], qr[2])
qc.h(qr[0])
qc.h(qr[1])
qc.measure(qr[0], cr[0])
qc.measure(qr[1], cr[1])