import cirq
q = cirq.LineQubit.range(3)
circuit = cirq.Circuit()
circuit.append([cirq.H(q[0]), cirq.H(q[1]), cirq.H(q[2])])
circuit.append(cirq.CCZ(q[0], q[1], q[2]))
circuit.append([cirq.H(q[0]), cirq.H(q[1]), cirq.H(q[2])])
circuit.append([cirq.X(q[0]), cirq.X(q[1]), cirq.X(q[2])])
circuit.append(cirq.H(q[2]))
circuit.append(cirq.CCZ(q[0], q[1], q[2]))
circuit.append(cirq.H(q[2]))
circuit.append([cirq.X(q[0]), cirq.X(q[1]), cirq.X(q[2])])
circuit.append([cirq.H(q[0]), cirq.H(q[1]), cirq.H(q[2])])