from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
qr = QuantumRegister(3)
cr = ClassicalRegister(3)
qc = QuantumCircuit(qr, cr)
qc.h(qr[0])
qc.h(qr[1])
qc.h(qr[2])
qc.ccz(qr[0], qr[1], qr[2])
qc.h(qr[0]); qc.h(qr[1]); qc.h(qr[2])
qc.x(qr[0]); qc.x(qr[1]); qc.x(qr[2])
qc.ccz(qr[0], qr[1], qr[2])
qc.x(qr[0]); qc.x(qr[1]); qc.x(qr[2])
qc.h(qr[0]); qc.h(qr[1]); qc.h(qr[2])
qc.measure(qr[0], cr[0])
qc.measure(qr[1], cr[1])
qc.measure(qr[2], cr[2])
