from qiskit import QuantumCircuit, QuantumRegister
qr = QuantumRegister(3)
qc = QuantumCircuit(qr)
qc.h(qr[0])
qc.h(qr[1])
qc.h(qr[2])
qc.ccz(qr[0], qr[1], qr[2])
qc.h(qr[0]); qc.h(qr[1]); qc.h(qr[2])
qc.x(qr[0]); qc.x(qr[1]); qc.x(qr[2])
qc.h(qr[2])
qc.ccz(qr[0], qr[1], qr[2])
qc.h(qr[2])
qc.x(qr[0]); qc.x(qr[1]); qc.x(qr[2])
qc.h(qr[0]); qc.h(qr[1]); qc.h(qr[2])