dev = qml.device("default.qubit", wires=3)
@qml.qnode(dev)
def grover():
    qml.Hadamard(wires=0)
    qml.Hadamard(wires=1)
    qml.Hadamard(wires=2)
    qml.ctrl(qml.PauliZ, control=[0, 1])(wires=2)
    qml.Hadamard(wires=0)
    qml.Hadamard(wires=1)
    qml.Hadamard(wires=2)
    qml.PauliX(wires=0)
    qml.PauliX(wires=1)
    qml.PauliX(wires=2)
    qml.Hadamard(wires=2)
    qml.ctrl(qml.PauliZ, control=[0, 1])(wires=2)
    qml.Hadamard(wires=2)
    qml.PauliX(wires=0)
    qml.PauliX(wires=1)
    qml.PauliX(wires=2)
    qml.Hadamard(wires=0)
    qml.Hadamard(wires=1)
    qml.Hadamard(wires=2)
    return qml.state()